Add informative messages with colorized output

diff --git a/puppet-openstack-configure b/puppet-openstack-configure
--- a/puppet-openstack-configure
+++ b/puppet-openstack-configure
@@ -1,30 +1,69 @@
 #!/bin/bash
 
+installpkg() {
+    if ! dpkg -s $1 &>/dev/null; then
+        aptitude -y install $1
+    fi
+}
+
+RESTORE='\033[0m'
+
+RED='\033[00;31m'
+GREEN='\033[00;32m'
+YELLOW='\033[00;33m'
+BLUE='\033[00;34m'
+PURPLE='\033[00;35m'
+CYAN='\033[00;36m'
+LIGHTGRAY='\033[00;37m'
+
+LRED='\033[01;31m'
+LGREEN='\033[01;32m'
+LYELLOW='\033[01;33m'
+LBLUE='\033[01;34m'
+LPURPLE='\033[01;35m'
+LCYAN='\033[01;36m'
+WHITE='\033[01;37m'
+
+msg() {
+    case "$1" in
+        error)  echo -ne "$RED";    echo "$0 error: ${@:2}";   echo -ne "$RESTORE"    >&2;;
+        warn)   echo -ne "$YELLOW"; echo "$0 warn: ${@:2}";    echo -ne "$RESTORE"    >&2;;
+        *)      echo -ne "$GREEN";  echo "$0 info: ${@}";    echo -ne "$RESTORE"    >&2;;
+    esac
+}
+
 hostname=$1
 controller_host=$2
 controller_ip=$3
 
-if (($#<3)); then
-    echo "usage: $0 hostname controller_host controller_ip" >&2
+if ((UID!=0)); then
+    msg error "This script needs to be run as root"
     exit 1
 fi
 
-installpkg() {
-    if ! dpkg -s $1 &>/dev/null; then
-        sudo aptitude -y install $1
-    fi
-}
+if (($#<3)); then
+    msg error "Invalid command-line arguments"
+    msg warn ""
+    msg warn "usage: $0 hostname controller_host controller_ip"
+    msg warn ""
+    msg warn "     example $0 vpc-compute2.ec2.local vpc-controller.ec2.local 10.0.0.64"
+    msg warn ""
+    exit 1
+fi
 
-sudo hostname $hostname
+msg "Setting hostname: $hostname"
+hostname $hostname
 echo $(hostname) > /etc/hostname
 grep -q $hostname /etc/hosts || echo "127.0.0.1 $(hostname)" >> /etc/hosts
 grep -q $controller_ip /etc/hosts || echo "$controller_ip $controller_host" >> /etc/hosts
 
+msg "Adding repository: PuppetLabs"
 if ! dpkg -s puppetlabs-release &>/dev/null; then
     wget -nc -P /tmp http://apt.puppetlabs.com/puppetlabs-release-precise.deb
     dpkg -i /tmp/puppetlabs-release-precise.deb
 fi
 
+msg "Adding repository: Ubuntu Cloud"
 installpkg ubuntu-cloud-keyring
 
 if [ ! -f /etc/apt/sources.list.d/ubuntu-cloud.list ]; then
@@ -41,13 +80,18 @@ EOF
     aptitude update
 fi
 
+msg "Installing: git"
 installpkg git
+
+msg "Installing: puppet"
 installpkg puppet
 
 if [[ $hostname == $controller_host ]]; then
+    msg "Installing: puppetmaster"
     installpkg puppetmaster
 fi
 
+msg "Installing Puppet modules: openstack"
 if  [ ! -d /etc/puppet/modules/openstack ]; then
     puppet module install puppetlabs-openstack
     mkdir -p /root/{src,backup}; cd /root/src
@@ -61,6 +105,7 @@ if  [ ! -d /etc/puppet/modules/openstack ]; then
     cd -
 fi
 
+msg "Configuring: Puppet agent"
 if ! grep -q $controller_host /etc/puppet/puppet.conf; then
     cat >> /etc/puppet/puppet.conf << EOF
 [agent]
@@ -76,18 +121,13 @@ if [[ $controller_host == $hostname ]]; then
     sed -ie 's/multi_host.*/multi_host => false,/' /etc/puppet/manifests/site.pp
 fi
 
+msg "Running: Puppet agent. This may take a while"
 time puppet agent -t
 
-if (($?=!0)); then
-    cat >&2 << "EOF"
-
-Make sure certificate is signed on Puppet agent:
-    puppet cert list
-    puppet cert sign <key>
-
-Then run on node: `sudo puppet agent -t'
-
-EOF
+if (($?!=0)); then
+    msg error "Certificate needs to be signed on Puppet master:"
+    msg error "   puppet cert sign $hostname"
+    msg error "Then manually trigger update: \`puppet agent -t'"
 fi
 
 # vim: ts=4:sw=4:et
